# Generated by Django 4.2.16 on 2026-08-05 20:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicAssessment',
            fields=[
                ('assessment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assessment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('assessment_date', models.DateField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('learning_behaviour', models.CharField(blank=True, max_length=100, null=True)),
                ('narrative', models.TextField(blank=True, null=True)),
                ('intervention_plan', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'academic_assessment',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_date', models.DateField()),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('time_in', models.TimeField(blank=True, null=True)),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('absence_reason', models.TextField(blank=True, null=True)),
                ('participation_level', models.CharField(blank=True, max_length=100, null=True)),
                ('attention_level', models.CharField(blank=True, max_length=100, null=True)),
                ('behaviour', models.CharField(blank=True, max_length=100, null=True)),
                ('tutor_observation', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
        migrations.CreateModel(
            name='Center',
            fields=[
                ('centre_id', models.AutoField(primary_key=True, serialize=False)),
                ('centre_name', models.CharField(max_length=150)),
                ('centre_type', models.CharField(blank=True, max_length=50, null=True)),
                ('block', models.CharField(blank=True, max_length=100, null=True)),
                ('village', models.CharField(blank=True, max_length=100, null=True)),
                ('gps_location', models.CharField(blank=True, max_length=255, null=True)),
                ('facilitator_name', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'centre',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_id', models.AutoField(primary_key=True, serialize=False)),
                ('program_name', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'program',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectScore',
            fields=[
                ('subject_score_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(blank=True, max_length=100, null=True)),
                ('marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('understanding_level', models.CharField(blank=True, max_length=100, null=True)),
                ('application_ability', models.CharField(blank=True, max_length=100, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_scores', to='school.academicassessment')),
            ],
            options={
                'db_table': 'subject_score',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('student_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admission_number', models.CharField(max_length=20, unique=True)),
                ('roll_number', models.CharField(blank=True, max_length=20, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField()),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('caste', models.CharField(blank=True, max_length=50, null=True)),
                ('student_photo', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('class_id', models.UUIDField(blank=True, null=True)),
                ('section_id', models.UUIDField(blank=True, null=True)),
                ('admission_date', models.DateField()),
                ('previous_school', models.CharField(blank=True, max_length=200, null=True)),
                ('aadhar_number', models.CharField(blank=True, max_length=20, null=True)),
                ('birth_certificate_number', models.CharField(blank=True, max_length=50, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150, null=True)),
                ('emergency_contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_profiles', to='school.center')),
            ],
            options={
                'db_table': 'student_profile',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('nick_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
                ('school_name', models.CharField(blank=True, max_length=150, null=True)),
                ('school_type', models.CharField(blank=True, max_length=50, null=True)),
                ('class_grade', models.CharField(blank=True, max_length=30, null=True)),
                ('medium_of_instruction', models.CharField(blank=True, max_length=50, null=True)),
                ('attendance_pattern', models.CharField(blank=True, max_length=100, null=True)),
                ('previous_academic_performance', models.CharField(blank=True, max_length=100, null=True)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='school.center')),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.AutoField(primary_key=True, serialize=False)),
                ('region_name', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='school.program')),
            ],
            options={
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='LearningBehaviour',
            fields=[
                ('behaviour_id', models.AutoField(primary_key=True, serialize=False)),
                ('homework_completed', models.BooleanField(default=False)),
                ('classwork_completed', models.BooleanField(default=False)),
                ('asked_questions', models.BooleanField(default=False)),
                ('helped_others', models.BooleanField(default=False)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_behaviours', to='school.attendance')),
            ],
            options={
                'db_table': 'learning_behaviour',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('district_id', models.AutoField(primary_key=True, serialize=False)),
                ('district_name', models.CharField(max_length=100)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='school.region')),
            ],
            options={
                'db_table': 'district',
            },
        ),
        migrations.AddField(
            model_name='center',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='centres', to='school.district'),
        ),
        migrations.AddField(
            model_name='center',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='centres', to='school.region'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='school.student'),
        ),
        migrations.AddField(
            model_name='academicassessment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_assessments', to='school.student'),
        ),
    ]
