# Generated by Django 4.2.16 on 2026-08-06 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('family_id', models.AutoField(primary_key=True, serialize=False)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian', models.CharField(blank=True, max_length=100, null=True)),
                ('parent_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('father_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('father_education', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_education', models.CharField(blank=True, max_length=100, null=True)),
                ('family_members', models.IntegerField(blank=True, null=True)),
                ('school_going_children', models.IntegerField(blank=True, null=True)),
                ('birth_order', models.IntegerField(blank=True, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family', to='school.student')),
            ],
            options={
                'db_table': 'family',
            },
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
